version: '3'

services:
  mongodb:
    container_name: code-challenge-ze
    image: bitnami/mongodb:6.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/bitnami/mongodb

volumes:
  mongodb_data:
    driver: local
